# Generated by Django 3.2.3 on 2021-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('is_viewed', models.BooleanField(default=False)),
                ('date_sent', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=64)),
                ('resume_image', models.ImageField(upload_to='img/resumes')),
                ('is_viewed', models.BooleanField(default=False)),
                ('date_sent', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
